# Generated by Django 3.2.11 on 2022-01-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.IntegerField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, default=None, max_length=280, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_size', models.IntegerField()),
                ('image_url', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('notes', models.CharField(blank=True, default=None, max_length=280, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.camera')),
            ],
        ),
    ]
