# Generated by Django 2.2.6 on 2022-01-09 08:04
from django.db import migrations
import sys


class Migration(migrations.Migration):

    # Get SQL data.
    with open('default.sql', 'r') as sqlfile:
        sql = sqlfile.read()


    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql)  
    ] if 'test' not in sys.argv[1:] else []  # This took hours to figure out. Test Cases work again.


